title: Woo0's Dev Blog
description: '개발과 공부 기록을 담는 공간'
logo_img: '/assets/img/favicon.webp'
profile_img: '/assets/img/profile.webp'

# Social Links
email: jungwy98@gmail.com
github_username: Jung-kr
twitter_username: twitter
instagram_username: instagram
linkedin_username: linkedin
facebook_username: facebook

# External API
giscus_repo: 'Jung-kr/Jung-kr.github.io'
giscus_repoId: 'R_kgDOONju4A'
giscus_category: 'Announcements'
giscus_categoryId: 'DIC_kwDOONju4M4CoZht'
goatcounter_code: 'jung-kr'
google_analytics:

# If your repo name follows the format "<user-name>.github.io", then leave the below blank.
# Otherwise, set its value as "/<repo-name>". ex) baseurl: /myblog
baseurl:

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-loading-lazy

exclude:
  - docs/

collections:
  pages:
    output: true
    permalink: /:path.html

defaults:
  - scope:
      path: ''
      type: 'pages'
    values:
      layout: 'page'
      date: '1900-01-01'

# Markdown newline activator
kramdown:
  input: GFM
  hard_wrap: true
